"""core schema

Revision ID: 1b822ca2189e
Revises: 
Create Date: 2026-09-10 00:22:57.123705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b822ca2189e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('tg_user_id', sa.Integer(), nullable=True),
    sa.Column('first_name', sa.String(length=64), nullable=False),
    sa.Column('last_name', sa.String(length=64), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('bio', sa.String(length=140), nullable=False),
    sa.Column('session_file', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('has_2fa', sa.Boolean(), nullable=False),
    sa.Column('is_online', sa.Boolean(), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_reason', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_accounts_phone'), ['phone'], unique=True)
        batch_op.create_index('ix_accounts_status', ['status'], unique=False)
        batch_op.create_index('ix_accounts_tg_user_id', ['tg_user_id'], unique=False)

    op.create_table('app_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('ip', sa.String(length=128), nullable=False),
    sa.Column('user_agent', sa.String(length=512), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('app_sessions', schema=None) as batch_op:
        batch_op.create_index('ix_app_sessions_expires_at', ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_app_sessions_token_hash'), ['token_hash'], unique=True)

    op.create_table('app_settings',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('bulk_jobs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('success', sa.Integer(), nullable=False),
    sa.Column('failed', sa.Integer(), nullable=False),
    sa.Column('skipped', sa.Integer(), nullable=False),
    sa.Column('pending', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bulk_jobs', schema=None) as batch_op:
        batch_op.create_index('ix_bulk_jobs_status', ['status'], unique=False)

    op.create_table('gone_accounts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('tg_user_id', sa.Integer(), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=False),
    sa.Column('last_name', sa.String(length=64), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('old_serial', sa.Integer(), nullable=True),
    sa.Column('reason', sa.String(length=32), nullable=False),
    sa.Column('gone_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('gone_accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gone_accounts_phone'), ['phone'], unique=False)

    op.create_table('login_attempts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ip', sa.String(length=128), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('attempted_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('login_attempts', schema=None) as batch_op:
        batch_op.create_index('ix_login_attempts_ip_time', ['ip', 'attempted_at'], unique=False)

    op.create_table('pending_logins',
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('phone_code_hash', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('phone')
    )
    op.create_table('target_checks',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('target', sa.String(length=255), nullable=False),
    sa.Column('peer', sa.JSON(), nullable=True),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('target_checks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_target_checks_target'), ['target'], unique=False)

    op.create_table('account_status_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('account_status_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_account_status_history_account_id'), ['account_id'], unique=False)
        batch_op.create_index('ix_status_history_account_time', ['account_id', 'created_at'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index('ix_audit_logs_created_at', ['created_at'], unique=False)

    op.create_table('bulk_job_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.String(length=64), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('error_code', sa.String(length=128), nullable=True),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['job_id'], ['bulk_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'account_id', name='uq_bulk_job_account')
    )
    with op.batch_alter_table('bulk_job_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bulk_job_items_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bulk_job_items_job_id'), ['job_id'], unique=False)
        batch_op.create_index('ix_bulk_job_items_status', ['status'], unique=False)

    op.create_table('security_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('tg_msg_id', sa.Integer(), nullable=False),
    sa.Column('message_text', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'tg_msg_id', name='uq_security_account_msg')
    )
    with op.batch_alter_table('security_messages', schema=None) as batch_op:
        batch_op.create_index('ix_security_is_read', ['is_read'], unique=False)
        batch_op.create_index(batch_op.f('ix_security_messages_account_id'), ['account_id'], unique=False)
        batch_op.create_index('ix_security_received_at', ['received_at'], unique=False)

    op.create_table('target_check_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('target_check_id', sa.String(length=64), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_check_id'], ['target_checks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('target_check_id', 'account_id', name='uq_target_check_account')
    )
    with op.batch_alter_table('target_check_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_target_check_results_target_check_id'), ['target_check_id'], unique=False)

    op.create_table('telegram_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('session_file', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_connected_at', sa.DateTime(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'session_file', name='uq_tg_session_account_file')
    )
    with op.batch_alter_table('telegram_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_telegram_sessions_account_id'), ['account_id'], unique=False)
        batch_op.create_index('ix_tg_sessions_status', ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('telegram_sessions', schema=None) as batch_op:
        batch_op.drop_index('ix_tg_sessions_status')
        batch_op.drop_index(batch_op.f('ix_telegram_sessions_account_id'))

    op.drop_table('telegram_sessions')
    with op.batch_alter_table('target_check_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_target_check_results_target_check_id'))

    op.drop_table('target_check_results')
    with op.batch_alter_table('security_messages', schema=None) as batch_op:
        batch_op.drop_index('ix_security_received_at')
        batch_op.drop_index(batch_op.f('ix_security_messages_account_id'))
        batch_op.drop_index('ix_security_is_read')

    op.drop_table('security_messages')
    with op.batch_alter_table('bulk_job_items', schema=None) as batch_op:
        batch_op.drop_index('ix_bulk_job_items_status')
        batch_op.drop_index(batch_op.f('ix_bulk_job_items_job_id'))
        batch_op.drop_index(batch_op.f('ix_bulk_job_items_account_id'))

    op.drop_table('bulk_job_items')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_logs_created_at')
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('account_status_history', schema=None) as batch_op:
        batch_op.drop_index('ix_status_history_account_time')
        batch_op.drop_index(batch_op.f('ix_account_status_history_account_id'))

    op.drop_table('account_status_history')
    with op.batch_alter_table('target_checks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_target_checks_target'))

    op.drop_table('target_checks')
    op.drop_table('pending_logins')
    with op.batch_alter_table('login_attempts', schema=None) as batch_op:
        batch_op.drop_index('ix_login_attempts_ip_time')

    op.drop_table('login_attempts')
    with op.batch_alter_table('gone_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gone_accounts_phone'))

    op.drop_table('gone_accounts')
    with op.batch_alter_table('bulk_jobs', schema=None) as batch_op:
        batch_op.drop_index('ix_bulk_jobs_status')

    op.drop_table('bulk_jobs')
    op.drop_table('app_settings')
    with op.batch_alter_table('app_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_app_sessions_token_hash'))
        batch_op.drop_index('ix_app_sessions_expires_at')

    op.drop_table('app_sessions')
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_index('ix_accounts_tg_user_id')
        batch_op.drop_index('ix_accounts_status')
        batch_op.drop_index(batch_op.f('ix_accounts_phone'))

    op.drop_table('accounts')
    # ### end Alembic commands ###
